"""init

Revision ID: 183d7c475eb1
Revises:
Create Date: 2026-07-26 02:33:44.115106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "183d7c475eb1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_tag_name"), "content_tag", ["name"], unique=True)
    op.create_table(
        "field_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_field_tag_name"), "field_tag", ["name"], unique=True)
    op.create_table(
        "content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("url", sa.String(length=2083), nullable=False),
        sa.Column("poster", sa.String(length=2083), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("other", sa.JSON(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["content_tag.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_url"), "content", ["url"], unique=True)
    op.create_table(
        "field",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1023), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["field_tag.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_field_name"), "field", ["name"], unique=False)
    op.create_table(
        "connection_field_content",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["field.id"],
        ),
        sa.PrimaryKeyConstraint("content_id", "field_id"),
    )
    op.create_index(
        op.f("ix_connection_field_content_field_id"),
        "connection_field_content",
        ["field_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_connection_field_content_field_id"),
        table_name="connection_field_content",
    )
    op.drop_table("connection_field_content")
    op.drop_index(op.f("ix_field_name"), table_name="field")
    op.drop_table("field")
    op.drop_index(op.f("ix_content_url"), table_name="content")
    op.drop_table("content")
    op.drop_index(op.f("ix_field_tag_name"), table_name="field_tag")
    op.drop_table("field_tag")
    op.drop_index(op.f("ix_content_tag_name"), table_name="content_tag")
    op.drop_table("content_tag")
    # ### end Alembic commands ###
