"""add other table

Revision ID: 5e281ce0e9e9
Revises: 183d7c475eb1
Create Date: 2026-07-26 02:36:28.627941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e281ce0e9e9"
down_revision: Union[str, Sequence[str], None] = "183d7c475eb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hentai",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_table(
        "manga",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_table(
        "hentai_video",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hentai_id", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("dub", sa.String(length=1024), nullable=True),
        sa.Column("video_path", sa.String(length=512), nullable=False),
        sa.Column("m3u8_path", sa.String(length=512), nullable=False),
        sa.Column("thumbanil_path", sa.String(length=512), nullable=False),
        sa.Column("other", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hentai_id"], ["hentai.content_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manga_chapter",
        sa.Column("manga_id", sa.Integer(), nullable=False),
        sa.Column("chapter_number", sa.Integer(), nullable=False),
        sa.Column("chapter_name", sa.String(length=1024), nullable=True),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["manga_id"], ["manga.content_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("manga_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manga_chapter")
    op.drop_table("hentai_video")
    op.drop_table("manga")
    op.drop_table("hentai")
    # ### end Alembic commands ###
